PETSCDIR        = /home/eduardo/install/petsc-3.1-p5
CFLAGS	        = 
FFLAGS	        = -I${PETSC_DIR}/include/finclude
CPPFLAGS        =
FPPFLAGS        =
LOCDIR          = src/sys/examples/tutorials/
MANSEC          = Sys
CLEANFILES      = binaryoutput binaryoutput.info
POBCPPC         = /home/eduardo/projects/mestrado/pobcpp/pork/pobcppc
LIBPOBCPP       = /home/eduardo/projects/mestrado/pobcpp/libpobcpp/include
PETSC_INCLUDE	   =  -I${PETSC_DIR}/linux/include -I${PETSC_DIR}/include

vec:
	gcc vec.h ${PETSC_INCLUDE)
