# Generated by porkyc.  Defines:
#   CXX, CXXFLAGS, LIBPORK, REWRITER
include config.gen.mk

# Generated by porkyc
RULES = rules.gen.h


.PHONY: all clean

all: $(REWRITER)

clean:
	rm -f *.o *~ $(REWRITER)

$(REWRITER): $(REWRITER).o $(LIBPORK)
	$(CXX) $(CXXFLAGS) -o $@ $+

$(REWRITER).cc: Makefile $(RULES)
