ELSA_INCDIRS := -I$(ELSA_DIR)/smbase -I$(ELSA_DIR)/elkhound -I$(ELSA_DIR)/ast -I$(ELSA_DIR)
ELSA_INCFLAGS := -D__UNIX__ -DUSE_SERIAL_NUMBERS=1 -DNDEBUG -D__LINUX__ $(ELSA_INCDIRS)
LIBELSA := $(ELSA_DIR)/libelsa.a

PIGLET_INCDIRS := -I$(PIGLET_DIR)
PIGLET_INCFLAGS := -I$(PIGLET_DIR)

CXXFLAGS := $(CONFIG_CXXFLAGS) $(ELSA_INCFLAGS) $(PIGLET_INCFLAGS)

LIBPORK := $(PIGLET_DIR)/libpork.a
