#!/bin/bash
src=$1
suffix=".temp.cpp"
temp=$src$suffix
if [ -e $src ]; then
	echo "#include \"pobcpp.h\"" > $temp
	cat "$src" >> $temp
	g++-4.1.2 -E -Wp,-K $temp > $temp".ii"
	./pobcpp $temp $temp".ii"
else
	echo "File not found"
fi
